### ISSUE TITLE
Growl/PushBullet style notifications

### ISSUE THREAD

**Issue by Chrisazy** [Gocnak/Botnak#107]
Lots of things this could be used for:
 - Followed streamer went live
 - New person in chat
 - New sub
 - Donor
 - Mention

Of course, this would be something you could disable, probably individual ones. I'd especially appreciate the mention one.

**Comment by Gocnak** [comment]
I mean I have Topic Tabs planned (#13) which will handle things like new donors/subs in their own tabs, questions and whatnot.

But I can still look into making little balloon notifications as well with a System Tray icon.
https://docs.oracle.com/javase/tutorial/uiswing/misc/systemtray.html

**Comment by Gocnak** [comment]
Not gonna do it for new person in chat, I think that's something the streamer should be able to determine.

Otherwise, very good examples of useful cases, I'm in the process of adding the toggles and will eventually support most of these.

**Comment by Gocnak** [comment]
Added in commit ddd8fc598f04ae44ec4378ab6b6699c6f4ac40e2 (forgot to close it)
