### ISSUE TITLE
Text being cut off at the end of the window

### ISSUE THREAD

**Issue by PopRocksJesus** [Gocnak/Botnak#108]
![](http://i.gyazo.com/5c582378ebad89e0c15686a16468d114.png)
![](http://i.gyazo.com/7dbd01817c960db8e5a7a609f03da5d8.png)
Yes that is the whole window. it is actually getting cut off
EDIT : added another shot for referance

**Comment by Gocnak** [comment]
Does resizing it fix it?

**Comment by PopRocksJesus** [comment]
Yes, I was using at the smallest size lengthwise. After making it a little larger and putting it back to the smaller size the text was pushed to the next line.

**Comment by PopRocksJesus** [comment]
Yes, I was using at the smallest size lengthwise. After making it a little larger and putting it back to the smaller size the text was pushed to the next line.

**Comment by Gocnak** [comment]
Re-open/comment on this issue if it happens again.

**Comment by PopRocksJesus** [comment]
![screenshot 2015-08-03 13 30 38](https://cloud.githubusercontent.com/assets/8473002/9043538/22ee0e86-39e4-11e5-8c21-96d6b6682668.png)
Just now

**Comment by Gocnak** [comment]
Ah wait I should add, you should test this on the new build. After I finish up GUIStreams I'll send you a test build.

I'm thinking it's the icons from the subscriber/donation messages that could potentially break it, as well as spamming faces in a row. Something with icons.

**Comment by PopRocksJesus** [comment]
Yea ill test further in that build no rush.

**Comment by PopRocksJesus** [comment]
![screenshot 2015-08-07 23 00 48](https://cloud.githubusercontent.com/assets/8473002/9148796/60737ef4-3d58-11e5-8894-18a8e3f47380.png)
 Just now

**Comment by Gocnak** [comment]
May have been fixed with the recent commit, re-open if issue continues.
