### ISSUE TITLE
Unable to set Title/Game

### ISSUE THREAD

**Issue by Jordod** [Gocnak/Botnak#112]
Whenever I try and set my title or game it returns a 401 even though I've authorised it to be able to set them.
![image](https://cloud.githubusercontent.com/assets/13240396/8627395/b2023b24-2742-11e5-9d17-af0cc6b61708.png)

**Comment by Gocnak** [comment]
Does this still happen?

**Comment by Jordod** [comment]
Just tested it, still happens

**Comment by Gocnak** [comment]
Try re-authenticating, check the boxes in the account GUI that say "edit status" and see if the error still happens.

**Comment by Gocnak** [comment]
Closing this for now, new Authorize GUI pushed and if this still occurs I'll fix it then.
