### ISSUE TITLE
Not receiving all messages in very large chats

### ISSUE THREAD

**Issue by Chrisazy** [Gocnak/Botnak#115]
I tested this with several of the front page chats, like riotgames, with 150k viewers, and dreamhacksc2 with ~10k viewers. The riotgames chat was getting sparse messages, maybe as many as 1%, while the 10k stream was getting virtually none (I only just now got 1 as I was writing this issue, after 10 minutes). Chat is working the other way, however. I can type and it shows up right away in the twitch chat. Obviously I've confirmed that there is chat happening in these streams, I'm just not getting it. I have no problems with streams >1k that I can notice

**Comment by Chrisazy** [comment]
Something interesting, I'm getting all of the "XXX was timed out/banned" messages. My riotgames chat had 10 of those and only a couple real messages.

**Comment by Gocnak** [comment]
Those are event chat servers. You'd have to connect to them to get the chat, as they aren't under the irc.twitch.tv domain redirect.

**Comment by Chrisazy** [comment]
Gotcha. Weird that I was still getting some of the messages o.O
