### ISSUE TITLE
Resource and memory leak when clicking "Setup User Account" more than once

### ISSUE THREAD

**Issue by Kexerval** [Gocnak/Botnak#116]
The console will spew "Address currently in use" indefinitely until the process exhausts all memory. It also causes a ridiculous spike in CPU usage.

**Comment by mikesmiffy128** [comment]
I think I know why that'd happen. When you set up the account, Botnak starts a server to capture information from the browser that gets launched. If you try and start the server twice, the socket is already in use and I guess Botnak goes into a loop retrying. The solution would be to *not* retry in the event of a failure, but handle the error gracefully somehow.

**Comment by Kexerval** [comment]
It also never terminates those servers from looking at my memory usage increase.

**Comment by mikesmiffy128** [comment]
I'm sure it's supposed to exit the moment it gets a request. Maybe there's a bug causing it not to clean up properly.

**Comment by Gocnak** [comment]
Thank you, I will look into this and hopefully fix it for the next update.
