### ISSUE TITLE
Failure to load other users messages

### ISSUE THREAD

**Issue by PopRocksJesus** [Gocnak/Botnak#120]
![1](https://cloud.githubusercontent.com/assets/8473002/9151460/07a5f97c-3dd1-11e5-8f93-26b03c8aee39.png)
![2](https://cloud.githubusercontent.com/assets/8473002/9151461/07a6fe94-3dd1-11e5-9ccb-a8d7747ce918.png)

 This again. Nothing in the system logs is out of order.

**Comment by Gocnak** [comment]
This may have been a Twitch IRC issue, re-open if this happens again.
