### ISSUE TITLE
New Windows Don't Obey "Always On Top" Setting

### ISSUE THREAD

**Issue by gmansoliver** [Gocnak/Botnak#124]
If Always On Top mode is enabled, opening the settings window from Preferences -> Settings will create the settings window below the main Botnak window, and it cannot be brought ontop
![botnak always on top](https://cloud.githubusercontent.com/assets/8473003/9345638/0828e7fc-45e1-11e5-8366-4bbea82686e8.PNG)

**Comment by Gocnak** [comment]
Aha, easy fix, just send the main window to the back after setting all other windows to always on top.

Fixed in next push.

**Comment by Gocnak** [comment]
Actually, further re-reading made me realize that you were talking about creating new windows *after* setting the Always On Top setting.

Either way, still an easy fix, albeit a bit different than what I originally thought.

**Comment by gmansoliver** [comment]
New title accurately reflects the actual problem, I didn't realize to check with other windows in botnak.
