### ISSUE TITLE
[Request] Have botnak spit out a response to what a link is

### ISSUE THREAD

**Issue by KinamKrindar** [Gocnak/Botnak#24]
The version that is on here, when a link is linked in chat, botnak would respond with something along the lines of "unknown link, click at your own discression" or whatever it was. The version you'd linked no longer has it responding to the links.

Would be good to have it as an option to have botnak able to respond with whatever the page title is for whatever was linked.

**Comment by Gocnak** [comment]
I've added YouTube video parsing for title and author and duration, Twitch VOD parsing for title and author, and added back the URL-unshortener. Any further things to spit out will require their own issue.
