### ISSUE TITLE
[Issue] Tab-order on settings pages

### ISSUE THREAD

**Issue by KinamKrindar** [Gocnak/Botnak#34]
I realize you're working on the whole UI Re-Design and all, but figured I'd bring this up due to it being around right now in 2.22. When in the settings page, when trying to fill in the information for the different accounts, pressing tab should go from the user name to the password field for that username... currently it goes from the main username to the bot username then over to the main password, and then over to the bot password.

**Comment by Gocnak** [comment]
With the new account manager in the new Settings GUI, this shouldn't be a problem.
