### ISSUE TITLE
Remove "GhostingServer.java"

### ISSUE THREAD

**Issue by Gocnak** [Gocnak/Botnak#38]
This needs to be an issue so I don't forget about it before merging into master :P

**Comment by Kexerval** [comment]
What even was Ghosting server? Was this for ghosting mod?

**Comment by mikesmiffy128** [comment]
It's for Ghosting Mod. There's one in the Ghosting repository too which I think is actually less up-to-date. This should really be fixed.

**Comment by Gocnak** [comment]
Yeah I needed somewhere to code and test it so I quickly threw it into my Botnak project and forgot about it when I pushed. I'll fix this next update.
