### ISSUE TITLE
[Bug] Chat Settings won't remember when to clear chat.

### ISSUE THREAD

**Issue by AnUnknownMiner** [Gocnak/Botnak#55]
When I go to the logging & cleanup section of the Settings. With Clear The Chat box checked. And you modify the number of lines from 100 and save it. It won't remember what that number is, and will default to 100.

**Comment by Gocnak** [comment]
Turns out the JSpinner is not very happy when you type your value in there.

So I'm disabling the ability to type in it, and setting the spinner to use increments of 5 for every click.
