### ISSUE TITLE
[Request] Keep on top

### ISSUE THREAD

**Issue by KinamKrindar** [Gocnak/Botnak#6]
Possible option for keeping the window on top of others? (great for multi monitor setup and having maybe a browsing window with some info on it but still wanting to see chat)

**Comment by Gocnak** [comment]
This will be added in the new Settings GUI, which will be created after (most likely during) the rest of the features get coded for soft implementations.

**Comment by Gocnak** [comment]
Update: This will be under the "Preferences" in the new menu bar.
