### ISSUE TITLE
Not working under Linux

### ISSUE THREAD

**Issue by Kiwi-1995** [Gocnak/Botnak#69]
root@kiwi-xub:/home/kiwi# java -jar /home/kiwi/Downloads/Botnak.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: Boot : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
This is what error pops up when launching botnak.jar.
Yes I have updated to Java 8 latest.
There was no executable bit so Ubuntu would freak it's shit when trying to execute it, so I do chmod +X botnak.jar to give it such bit so it would execute, I don't know if this affects it shouldn't. It's literally just giving a permission to run on the system.

I ran it under root/administrator to give it extra privilages.

I'm running Xubuntu 14.10 LTS which is based off Ubuntu

Minor edit have ran it without giving it the execute bit just getting it straight from github and running it under terminal/cmdprompt and it still produces the same error.

**Comment by jhaye** [comment]
I think, those are the errors, which are caused by running latest Botnak builds on JRE7. Are you sure you updated JRE to version 8 and not just the JDK? Try this and it should run: https://www.liberiangeek.net/2012/09/install-oracle-java-8-jdk-jre-in-ubuntu-12-04/

**Comment by Kiwi-1995** [comment]
I did verify using java -version and it did say that java 8 was the version it was using, I've gone ahead and decided to remove all java installs and used the linked method that Jhaye has suggested.

Will post back with results afterwards.

**Comment by mikesmiffy128** [comment]
That should probably not be disregarded; it looks like a thread death which means part of Botnak has crashed which could cause weird issues with other code.
    I think Linux issues may be caused by Botnak making some slightly odd assumptions when picking a config directory: it should really save to the user directory on most systems - maybe AppData on Windows or Application Support on a Mac - but I believe the current codebase just gets the default directory for a file selection directory. On Windows this happens to point to My Documents but I have no idea where the heck it goes on other systems.
    As well as this, there are probably a bunch of other assumptions about the host OS - I'm pretty sure the filename validator (I think it's in Utils?) doesn't take operating system-specific details into account.

**Comment by Kiwi-1995** [comment]
Well in my case for linux it's created it's own directory in /home/username/Botnak for it's default. I have tried setting a custom directory and it seems to not save. It's just loading the defaults.
I have provided an image for what it is doing. I am starting Botnak under root/admin.
![2015-02-08-034014_1280x800_scrot](https://cloud.githubusercontent.com/assets/4647694/6092446/406e3d30-af44-11e4-8595-9fbdca136f9b.png)

**Comment by Gocnak** [comment]
"at util.settings.Settings.lambda$load$0(Settings.java:188)"

Oh hey, a null pointer I would have never caught! I'll fix this for the next push I'll do; the sub scanner was added without a null check, so don't worry, this is fixable. I plan to add a full barrage of settings for the new Settings GUI which would prevent the useless checks like scanning for subscribers.

But for now, a null check should suffice for it. Use v2.29, and make sure to make more issues here for when any more errors like these happen!
