### ISSUE TITLE
Ability to edit a command

### ISSUE THREAD

**Issue by ghost** [Gocnak/Botnak#70]
I was messing around with Botnak and the ability to edit a command if you mess it up might be useful, rather than removing it and re-adding it with the changes. Though its more of a convenience feature.

**Comment by Gocnak** [comment]
Ah yes, I had this before and realized it was doing exactly what removing and re-adding the command would do. 

I could re-add it no problem.

**Comment by Gocnak** [comment]
Upon further inspection, with how I bundled Arguments into text commands, the editcommand functionality would mess up if someone tried editing a command with arguments. So I won't add this, and you'll have to stick to removing and re-adding the new command.
