### ISSUE TITLE
REPLY_TYPE for Bot in Other Channels

### ISSUE THREAD

**Issue by Gocnak** [Gocnak/Botnak#76]
In the new settings GUI, have a toggle for if the Bot should tag along with you joining other channels. As of right now, the bot account only joins the main user's chat, and stays.

Off by default, but could be helpful for smaller streamers if they want some text commands in other people's chats.

**Comment by Gocnak** [comment]
Update to this, the bot is going to follow along no matter what, but this toggle is going to only affect it talking as if it were in the main user's chat.

**Comment by Palehors68** [comment]
Have you thought about having a setting where only the owner can issue botnak commands when in other people’s chats (in case the other streamer doesn’t want their chat spammed from your bot)?

**Comment by Gocnak** [comment]
Oh that can work, I can make it a REPLY_TYPE or something where the bot doesn't respond at all, responds to just the Botnak user, or responds to everyone.

**Comment by Gocnak** [comment]
Footnote: This only changes how Botnak replies to text commands and links pasted in chat. If you want to edit Botnak, do so in your own stream's chat. Furthermore, sounds have no reason to play from somebody else's chat.

I can always change these if need be, but for now, I have allowed text commands and link parsing requests to be the only response in others' chats.
