### ISSUE TITLE
Multiple line message is being cut after 1st line

### ISSUE THREAD

**Issue by Ethan-BB** [Gocnak/Botnak#92]
When message with multiple lines is copied into twitch chat, botnak cuts the message after a first line instead of showing whole message.

Tried with video requirements on this page: http://help.twitch.tv/customer/portal/articles/1253460-broadcast-requirements.

**Comment by Gocnak** [comment]
I need more information on this. Perhaps some pictures?

**Comment by Ethan-BB** [comment]
This is how it looks: http://i.imgur.com/7DmG6Re.png
Message is copied from link above.

**Comment by Gocnak** [comment]
The message gets truncated by Twitch IRC servers and not Botnak. Just tested with two web chats.

You can see if you have two chat windows of the same chat open that it gets cut to the first line. Sucks, I can't do anything in Botnak to fix this, since it's on Twitch's side.
