### ISSUE TITLE
Local user cannot add emotes

### ISSUE THREAD

**Issue by PopRocksJesus** [Gocnak/Botnak#97]
To have an emote added to botnak another user must use it first. 

Having a fresh botnak without having a twitchfaces.txt or twitchfaces folder and using an emote without having seen another user use the emote will result in just text. Users cannot add emotes themselves where as previously using the emote a second time would result in the emote appearing.

**Comment by Gocnak** [comment]
Solution is to parse emotesets only once per boot, to ensure you have all the emotes you can possibly say. Fixed for next version.
