### ISSUE TITLE
Appearing as the Bot account when typing in botnak

### ISSUE THREAD

**Issue by PopRocksJesus** [Gocnak/Botnak#98]
Occasionally you as the "User" will sometimes appear as to be using the bot account.
http://puu.sh/iMGDK/30b093a155.png

This is local only. As of right now I cannot reproduce it. It has happened to me but I have no proof on my end.

Log file where gman will appear to be using bot account locally with a broadcaster tag:
http://puu.sh/iMGQ3/fa47e961be.txt

**Comment by Gocnak** [comment]
Jordod noticed this upon logging out and in the Bot account in the Settings GUI.

Further testing needs to be done to determine exactly what causes this, but the re-write of the Settings GUI is eventually going to happen so this may no longer be an issue after that.

**Comment by Gocnak** [comment]
Update on this issue please, does this still happen? If so, how frequently?

**Comment by PopRocksJesus** [comment]
It doesn't appear to be happening but if it has I haven't seen it. Afaik it's no longer a problem.

**Comment by Gocnak** [comment]
Kk, re-open if it becomes an issue again.
